name: 14a - Ejemplo docker saluda
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  uso-python:
    runs-on: ubuntu-latest
    name: Uso acción docker python
    steps:
      - id: docker
        uses: brainsdevops/gha-dockerpy-hola@v1
        with:
          nombre: 'Juan'
      - name: El saludo
        run: echo "${{steps.docker.outputs.saludo}}"
